import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import './globals.css'
import { Provider } from './provider'

const montserrat = Montserrat({subsets: ['latin'], display: 'swap'})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <Provider 
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
            >
          {children}
        </Provider>
      </body>
    </html>
  )
}
